language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

os: linux
dist: xenial
  
install: "pip install -r requirements.txt"

script: pytest

notifications:
  email:
    on_success: never 
    on_failure: always
